#ifndef MODBUS_FUNCTIONS_H
#define MODBUS_FUNCTIONS_H

// Modbus Function Codes
#define MB_FUNCTION_READ_COILS                        1
#define MB_FUNCTION_READ_DISCRETE_INPUTS              2
#define MB_FUNCTION_READ_HOLDING_REGISTERS            3
#define MB_FUNCTION_READ_INPUT_REGISTERS              4
#define MB_FUNCTION_WRITE_SINGLE_COIL                 5
#define MB_FUNCTION_WRITE_SINGLE_HOLDING_REGISTER     6
#define MB_FUNCTION_WRITE_MULTIPLE_COILS              15
#define MB_FUNCTION_WRITE_MULTIPLE_HOLDING_REGISTERS  16

#endif // MODBUS_FUNCTIONS_H